### ISSUE TITLE
No window opens on MacOS

### ISSUE THREAD

**Issue by mabuchner** [Viladoman/SeeProfiler#1]
I tried to run the application on MacOS, but no window opens.

The following error is logged when running the application via the command line:

```
Error: Image could not be created from /Users/username/Downloads/SeeProfiler-darwin-x64/SeeProfiler.app/Contents/Resources/app/main/data/logo.ico
    at App.CreateWindow (/Users/username/Downloads/SeeProfiler-darwin-x64/SeeProfiler.app/Contents/Resources/app/app.js:39:9)
```

**Comment by Viladoman** [comment]
I only have Windows machines at the moment at home, so I could not test the deployments on either Linux or MacOS. It looks like it failed trying to get the icon for the main window. 

As a workaround, you can try commenting out the icon at the app.js: 
line 39: `win = new BrowserWindow({width: 1600, height: 900, show: false, //icon:path.join(__dirname, 'main', 'data', 'logo.ico'),`
line 80: `winObj.win = new BrowserWindow({width: 1400, height: 900, show: false,/* icon:path.join(__dirname, 'main', 'data', 'logo.ico'), */webPreferences: { nodeIntegration: true } })`

Hopefully this should be enough for the app to boot. 

Checking the documentation It looks like the icon needs to be in png (512x512) in order to work on all platforms [https://www.electron.build/icons](https://www.electron.build/icons). 

I will try getting my hands on an Apple computer meanwhile to make sure everything works as expected.

**Comment by mabuchner** [comment]
Commenting out the code worked. Resizing the icon to 512x512 didn't work.

**Comment by Viladoman** [comment]
Cool! I added all the potential icons, changed the app.js to ignore those icons in 'non-Windows' and re-exported on all platforms. You can try getting latest, it should work now. 

[Get Latest MacOS](https://github.com/Viladoman/SeeProfiler/releases/latest/download/SeeProfiler-macOS.zip)

**Comment by mabuchner** [comment]
Thanks.

Now the windows appears, but I get the following error in the console of the development tools

```
Uncaught TypeError: Cannot destructure property 'Menu' of 'remote' as it is undefined.
    at Object.<anonymous> (/Users/martin.buchne…/src/interface.js:3)
    at Object.<anonymous> (/Users/martin.buchne…rc/interface.js:122)
    at Module._compile (internal/modules/cjs/loader.js:1145)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166)
    at Module.load (internal/modules/cjs/loader.js:981)
    at Module._load (internal/modules/cjs/loader.js:881)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:1023)
    at require (internal/modules/cjs/helpers.js:77)
    at Object.<anonymous> (/Users/martin.buchne…/main/src/main.js:1)
```

Dragging a time trace JSON file into the window also doesn't seem to have any effect.

**Comment by Viladoman** [comment]
Good catch! It looks like some breaking changes were introduced in the last electron version and the new exports injected those issues. [Breaking change](https://github.com/electron/electron/blob/master/docs/breaking-changes.md#default-changed-enableremotemodule-defaults-to-false). 

Sorry about that. Re-exported again. Thanks for testing it on MacOS, I really appreciate it. 
[Get Latest MacOS](https://github.com/Viladoman/SeeProfiler/releases/latest/download/SeeProfiler-macOS.zip)

**Comment by mabuchner** [comment]
The latest version appears to be working fine on MacOS now.

Many thanks for the quick response and for creating such a useful tool.
